apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strategy-pvc
  namespace: quantrading
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 10Gi
